// flow-typed signature: 891591a45488874951d5117dc307ab7c
// flow-typed version: <<STUB>>/hyphenate-style-name_v^1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyphenate-style-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyphenate-style-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hyphenate-style-name/index' {
  declare module.exports: $Exports<'hyphenate-style-name'>;
}
declare module 'hyphenate-style-name/index.js' {
  declare module.exports: $Exports<'hyphenate-style-name'>;
}
